
# DELETE http://localhost:3000/questions/5de9a1e04186599a2e7a274c
# GET http://localhost:3000/questions/5de99940730924648f721add
# GET http://localhost:3000/questions

# POST http://localhost:3000/questions
# Content-Type: application/json

# {
#     "question": "What character is う",
#     "answer": "u",
#     "difficulty": "beginner"
# }

PATCH http://localhost:3000/questions/5de9a4264186599a2e7a274f
Content-Type: application/json

{
    "question": "What character is う",
    "answer": "u",
    "difficulty": "beginner"
}